import Head from "next/head";
import Image from "next/image";
import busImg from "../../../public/white-bus.svg";
import styles from "@/styles/Home.module.css";
import styles1 from "@/styles/BookTrip.module.css";
import Button from "@/components/Button";
import { useRouter } from "next/router";
import { FormEvent } from "react";

export default function Login() {
  const router = useRouter();
  const handleLogin = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (
      e.currentTarget.passcode.value === process.env.NEXT_PUBLIC_ADMIN_PASSCODE
    ) {
      router.push("/travellers");
    } else {
      alert("wrong passcode!");
    }
  };
  return (
    <>
      <Head>
        <title>RML Sunday Trips</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container min-full-height text-center flex flex-col justify-content-center align-items-center">
        <Image src={busImg} alt="Bus Image" className={styles.busImg} />
        <h1 className={`${styles.h1} text-white`}>Pilot Login</h1>
        <form onSubmit={handleLogin}>
          <div className={`${styles.inputDiv} my-min`}>
            <input
              className={styles1.inputField}
              type="text"
              id="passcode"
              name="passcode"
              placeholder="Passcode"
              required
            />
          </div>
          <Button type="submit" variant="secondary" btnText="Login" />
        </form>
      </main>
    </>
  );
}
