import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/BookTrip.module.css";
import blueBus from "../../../public/blue-bus.svg";
import Button from "@/components/Button";
import { useRouter } from "next/router";

export default function BookingSuccessful() {
  const router = useRouter();
  const goBack = () => {
    router.push("/");
  };

  return (
    <>
      <Head>
        <title>RML Sunday Trips | Book Trip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container min-full-height white-wrapper text-center flex flex-col justify-content-center align-items-center">
        <Image src={blueBus} alt="Bus Image" className={styles.busImg} />
        <h1 className={`secondary-text my-min`}>
          Thanks for booking, the pilot will be in touch 🤙🏽
        </h1>
        <Button variant="secondary" btnText="Go Home" handleClick={goBack} />
      </main>
    </>
  );
}
