import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/BookTrip.module.css";
import blueBus from "../../../public/blue-bus.svg";
import { supabase } from "@/lib/supabaseClient";
import Link from "next/link";
import React from "react";

interface Traveller {
  id: string;
  family_name: string;
  address_line_1: string;
  post_code: string;
}

interface TravellersProps {
  travellers: Traveller[];
}

export default function Travellers({ travellers }: TravellersProps) {
  return (
    <>
      <Head>
        <title>RML Sunday Trips | Book Trip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container min-full-height white-wrapper">
        <Link href="/">
          <Image src={blueBus} alt="Bus Image" className={styles.busImg} />
        </Link>
        <h1 className={`secondary-text my-min`}>Travellers</h1>
        <ul>
          {travellers.map((traveller: Traveller) => (
            <React.Fragment key={traveller.id}>
              <li
                className="my-min"
                style={{
                  listStyle: "none",
                  padding: 15,
                  border: "solid thin",
                }}
              >
                {traveller.family_name} family
                <br />
                {traveller.address_line_1}
                {", "}
                {traveller.post_code}
              </li>
            </React.Fragment>
          ))}
        </ul>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let { data } = await supabase.from("travellers").select();
  return {
    props: {
      travellers: data,
    },
  };
}
