import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Button from "@/components/Button";
import busImg from "../../public/white-bus.svg";
import AdminIcon from "../../public/admin-icon.svg";

import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  const router = useRouter();
  const handleBooking = () => {
    router.push("/book-trip");
  };
  return (
    <>
      <Head>
        <title>RML Sunday Trips</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container min-full-height text-center flex flex-col justify-content-center align-items-center">
        <Image src={busImg} alt="Bus Image" className={styles.busImg} />
        <h1 className={`${styles.h1} text-white`}>
          Joining the bus this sunday?
        </h1>
        <Button
          variant="secondary"
          btnText="Book Trip"
          handleClick={handleBooking}
        />
        <Link href="/login">
          <Image
            className="pos-abs"
            style={{ bottom: 50, right: 50 }}
            src={AdminIcon}
            alt="Admin Icon"
            role="button"
          />
        </Link>
      </main>
    </>
  );
}
