import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/BookTrip.module.css";
import blueBus from "../../../public/blue-bus.svg";

export default function BookTrip() {
  return (
    <>
      <Head>
        <title>RML Sunday Trips | Book Trip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container white-wrapper text-center flex flex-col justify-content-center align-items-center">
        <Image src={blueBus} alt="Bus Image" className={styles.busImg} />
        <h1 className={`${styles.h1} primary-text`}>Your Details</h1>
        <div className={styles.hr}></div>
        <p className={styles.loadingText}>loading form...</p>
      </main>
    </>
  );
}
